-- Create manager_roles table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.manager_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id BIGINT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('shop_owner', 'team_leader', 'technician')),
    shop_name TEXT,
    is_active BOOLEAN DEFAULT true,
    email TEXT, -- Added for Password Login
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add email column if table existed but column didn't (idempotent)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'manager_roles' AND column_name = 'email') THEN
        ALTER TABLE public.manager_roles ADD COLUMN email TEXT;
    END IF;
END $$;

-- Enable RLS
ALTER TABLE public.manager_roles ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Public read manager_roles" ON public.manager_roles FOR SELECT USING (true);
CREATE POLICY "Admin full access manager_roles" ON public.manager_roles FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_manager_roles_athlete_id ON public.manager_roles(athlete_id);
CREATE INDEX IF NOT EXISTS idx_manager_roles_email ON public.manager_roles(email);

-- Comments
COMMENT ON TABLE public.manager_roles IS 'Stores manager roles and permissions';
COMMENT ON COLUMN public.manager_roles.email IS 'Linked Supabase Auth email for password login';
